/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Factura;
import Modelo.ReferenciasRopa;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class frmDetalleFactura extends javax.swing.JFrame {

    /**
     * Creates new form frmDetalleFactura
     */
    public frmDetalleFactura() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDetalleFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDetalle = new javax.swing.JTextArea();
        cbxIdProducto = new javax.swing.JComboBox<>();
        cbxCodigo = new javax.swing.JComboBox<>();
        jFormattedTxtValorTotal = new javax.swing.JFormattedTextField();
        jFormattedTxtValorUnitario = new javax.swing.JFormattedTextField();
        jFormattedTxtCantidad = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        txtIdDetalle = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxIdFactura = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(153, 204, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblDetalleFactura.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TblDetalleFactura.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TblDetalleFactura.setCellSelectionEnabled(true);
        TblDetalleFactura.setRowHeight(25);
        jScrollPane1.setViewportView(TblDetalleFactura);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 830, 120));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Detalle");
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Precio Unitario");
        pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Valor Total");
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Codigo");
        pnlPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Precio");
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        txtAreaDetalle.setColumns(20);
        txtAreaDetalle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtAreaDetalle.setRows(5);
        jScrollPane2.setViewportView(txtAreaDetalle);

        pnlPrincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 470, -1));

        cbxIdProducto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbxIdProducto.setName(""); // NOI18N
        pnlPrincipal.add(cbxIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 210, -1));

        cbxCodigo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pnlPrincipal.add(cbxCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 210, -1));

        jFormattedTxtValorTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pnlPrincipal.add(jFormattedTxtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 210, -1));

        jFormattedTxtValorUnitario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pnlPrincipal.add(jFormattedTxtValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));

        jFormattedTxtCantidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pnlPrincipal.add(jFormattedTxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, -1));

        btnBuscar.setBackground(new java.awt.Color(51, 102, 0));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 3, 16)); // NOI18N
        btnBuscar.setText("Buscar");
        pnlPrincipal.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 120, -1));

        txtIdDetalle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pnlPrincipal.add(txtIdDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 102, 0));
        btnRegistrar.setFont(new java.awt.Font("Arial Black", 3, 16)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseReleased(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        btnModificar.setBackground(new java.awt.Color(51, 102, 0));
        btnModificar.setFont(new java.awt.Font("Arial Black", 3, 16)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnModificarMouseReleased(evt);
            }
        });
        pnlPrincipal.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Arial Black", 3, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEliminarMouseReleased(evt);
            }
        });
        pnlPrincipal.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 120, -1));

        btnLimpiar.setBackground(new java.awt.Color(51, 102, 0));
        btnLimpiar.setFont(new java.awt.Font("Arial Black", 3, 16)); // NOI18N
        btnLimpiar.setText("Limpiar");
        pnlPrincipal.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 120, -1));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlPrincipal.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 160, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Id Factura");
        pnlPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        cbxIdFactura.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pnlPrincipal.add(cbxIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 210, -1));

        btnMostrar.setText("jButton1");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMousePressed
        btnRegistrar.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnRegistrarMousePressed

    private void btnRegistrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseReleased
        btnRegistrar.setBackground(Color.green);
    }//GEN-LAST:event_btnRegistrarMouseReleased

    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed
        btnModificar.setBackground(Color.blue);
    }//GEN-LAST:event_btnModificarMousePressed

    private void btnModificarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseReleased
        btnModificar.setBackground(Color.cyan);
    }//GEN-LAST:event_btnModificarMouseReleased

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        btnEliminar.setBackground(Color.yellow);
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseReleased
        btnEliminar.setBackground(Color.red);
    }//GEN-LAST:event_btnEliminarMouseReleased

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        //int Id = cbxIdFactura.getSelectedIndex();
        //JOptionPane.showMessageDialog(null, "Selecionó la opción " + Id);
        
        //int IdFatura = cbxIdFactura.getItemAt(cbxIdFactura.getSelectedIndex()).getIdFactura();
        //JOptionPane.showMessageDialog(null, "Selecionó la opción " + IdFatura);
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetalleFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetalleFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetalleFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetalleFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetalleFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TblDetalleFactura;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JComboBox<Object> cbxCodigo;
    public javax.swing.JComboBox<Factura> cbxIdFactura;
    public javax.swing.JComboBox<Object> cbxIdProducto;
    public javax.swing.JFormattedTextField jFormattedTxtCantidad;
    public javax.swing.JFormattedTextField jFormattedTxtValorTotal;
    public javax.swing.JFormattedTextField jFormattedTxtValorUnitario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlPrincipal;
    public javax.swing.JTextArea txtAreaDetalle;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtIdDetalle;
    // End of variables declaration//GEN-END:variables
}
