/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.KeyEvent;

/**
 *
 * @author ASUS
 */
public class frmRopaTerminada extends javax.swing.JFrame {

    /**
     * Creates new form RopaTerminada
     */
    public frmRopaTerminada() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRopaTerminada = new javax.swing.JTable();
        txtTalla = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecioElaboracion = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 153, 51));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCodigo.setText("Código");
        pnlPrincipal.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Talla");
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Color");
        pnlPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Stock");
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("PrecIo Elaboración");
        pnlPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Precio Venta");
        pnlPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        tblRopaTerminada.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        tblRopaTerminada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRopaTerminada.setAlignmentX(0.8F);
        tblRopaTerminada.setAlignmentY(0.8F);
        tblRopaTerminada.setGridColor(new java.awt.Color(0, 102, 0));
        tblRopaTerminada.setMaximumSize(new java.awt.Dimension(8, 4));
        tblRopaTerminada.setMinimumSize(new java.awt.Dimension(8, 4));
        tblRopaTerminada.setRowHeight(30);
        tblRopaTerminada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRopaTerminadaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRopaTerminada);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 860, 180));

        txtTalla.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pnlPrincipal.add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, -1));

        txtColor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });
        pnlPrincipal.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, -1));

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        pnlPrincipal.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, -1));

        txtPrecioElaboracion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPrecioElaboracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioElaboracionKeyTyped(evt);
            }
        });
        pnlPrincipal.add(txtPrecioElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, -1));

        txtPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });
        pnlPrincipal.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 200, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 153, 0));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        pnlPrincipal.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, -1));

        btnModificar.setBackground(new java.awt.Color(51, 153, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnModificar.setText("Modificar");
        pnlPrincipal.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 120, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        pnlPrincipal.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, -1));

        btnLimpiar.setBackground(new java.awt.Color(51, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        pnlPrincipal.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 120, -1));

        btnBuscar.setBackground(new java.awt.Color(51, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        pnlPrincipal.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 120, -1));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 70, -1));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnlPrincipal.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("LISTA DE PRODUCTOS LISTOS PARA LA VENTA");
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnlPrincipal.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 30));

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pnlPrincipal.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Descripcion");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        //Con esta variable logramos que el campo txtColor no reciba números, sólo las letras d la a a la z..
        char c = evt.getKeyChar();
        if((c<'a' || c>'z' )&& (c<'A') |c>'Z'&& c !=KeyEvent.VK_SPACE)evt.consume();
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        //Con esta variable logramos que el campo txtStock no reciba letras, sólo números.
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'  )evt.consume();
        //Con esta condición se limita el campo TxtTelefono a recibir tan sólo 10 números.
        if(txtStock.getText().length()>=5){
        evt.consume();
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtPrecioElaboracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioElaboracionKeyTyped
        //Con esta variable logramos que el campo txtPrecioElaboracion no reciba letras, sólo números.
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'  )evt.consume();
        //Con esta condición se limita el campo TxtTelefono a recibir tan sólo 6 números.
        if(txtPrecioElaboracion.getText().length()>=6){
        evt.consume();
        }
    }//GEN-LAST:event_txtPrecioElaboracionKeyTyped

    private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
        //Con esta variable logramos que el campo txtPrecioVenta no reciba letras, sólo números.
        char c = evt.getKeyChar();
        if(c<'0' || c>'9'  )evt.consume();
        //Con esta condición se limita el campo TxtTelefono a recibir tan sólo 6 números.
        if(txtPrecioVenta.getText().length()>=6){
        evt.consume();
        }
    }//GEN-LAST:event_txtPrecioVentaKeyTyped

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tblRopaTerminadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRopaTerminadaMouseClicked
        int fila = tblRopaTerminada.rowAtPoint(evt.getPoint());
        txtId.setText(tblRopaTerminada.getValueAt(fila, 0).toString());
        txtCodigo.setText(tblRopaTerminada.getValueAt(fila, 1).toString());
        txtDescripcion.setText(tblRopaTerminada.getValueAt(fila, 2).toString());
        txtTalla.setText(tblRopaTerminada.getValueAt(fila, 3).toString());
        txtColor.setText(tblRopaTerminada.getValueAt(fila, 4).toString());
        txtStock.setText(tblRopaTerminada.getValueAt(fila, 5).toString());
        txtPrecioElaboracion.setText(tblRopaTerminada.getValueAt(fila, 6).toString());
        txtPrecioVenta.setText(tblRopaTerminada.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tblRopaTerminadaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRopaTerminada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRopaTerminada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRopaTerminada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRopaTerminada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRopaTerminada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JPanel pnlPrincipal;
    public javax.swing.JTable tblRopaTerminada;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtColor;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtPrecioElaboracion;
    public javax.swing.JTextField txtPrecioVenta;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtTalla;
    // End of variables declaration//GEN-END:variables
}
